I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 168, in script
    show isaac angry zoom 1.6
Exception: Image 'isaac angry' does not accept attributes 'zoom 1 .6'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 168, in script
    show isaac angry zoom 1.6
  File "renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 744, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/core.py", line 390, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'isaac angry' does not accept attributes 'zoom 1 .6'.

Windows-10-10.0.22000
Ren'Py 7.4.9.2142
Oatmeal with Jerma 1.0
Sun Mar 27 16:33:02 2022
